fix white space
unfoldingWord/usfm-js pull request #101
Opened 2021-09-03 03:19 UTC by da1nerd

See https://github.com/unfoldingword/translationcore/issues/7164

\p should not have any trailing spaces before the newline

2021-09-06 03:35 UTC, RobH123 commented
@da1nerd I noticed these warnings in a USFM check today, and wondered if they might also be covered by this set of changes:
LT Unexpected USFM field with 'line marker='\w'' at EXO 6:14 in en_ult repository in file 02-EXO.usfm on line 3,895 around ◗fathers:␣\p◖ (Priority 875)
LT Unexpected USFM field with 'line marker='\zaln-s'' at EXO 6:23 in en_ult repository in file 02-EXO.usfm on line 4,114 around ◗Ithamar.\p␣␣◖ (Priority 875)
LT Unexpected USFM field with 'line marker='\w'' at EXO 6:29 in en_ult repository in file 02-EXO.usfm on line 4,253 around ◗you.”\p␣␣◖ (Priority 875)
ST Unexpected USFM field with 'line marker='\w'' at EXO 6:14 in en_ust repository in file 02-EXO.usfm on line 4,120 around ◗leaders.\p◖ (Priority 875)
ST Unexpected USFM field with 'line marker='\w'' at EXO 6:14 in en_ust repository in file 02-EXO.usfm on line 4,140 around ◗them.\p␣␣◖ (Priority 875)
ST Unexpected USFM field with 'line marker='\w'' at EXO 6:29 in en_ust repository in file 02-EXO.usfm on line 4,429 around ◗you.”\p␣␣◖ (Priority 875)

Could it also be USFM-JS sometimes appending \p markers to the ends of lines and often with superfluous spaces before or after?

2021-09-06 18:18 UTC, da1nerd commented
@RobH123 I'm making some additional tweaks to fix those bugs you mentioned.
In doing so I ended up changing some other things I'd like to run by you.

* Is it ok to eliminate all blank lines from usfm except for a blank line at the end of the file? This would include removing blank lines before \s5 markers
* Is it ok to eliminate all white space at the end of each line of usfm?

2021-09-06 21:09 UTC, RobH123 commented
Great! I'm glad I noticed those while your mind was still in here. I'd forgotten that it often did that.

No to #1. Please leave blank lines in. The editors use them for visual breaks. They do no harm.

If you wanted, I think it would be ok to normalise two or more blank lines just to one.

Please ensure that the file ends with a newline.

Yes to #2. I know of no need to ever have trailing spaces.

Thanks @da1nerd .

2021-09-07 14:43 UTC, PhotoNomad0 requested changes

2021-09-07 14:43 UTC, PhotoNomad0 commented on __tests__/resources/acts-1-20.aligned.oldformat.usfm
> +\zaln-s |x-strong="G10630" x-lemma="γάρ" x-morph="Gr,CC,,,,,,,," x-occurrence="1" x-occurrences="1" x-content="γὰρ"
We should leave the spaces in this file.  This is to verify that we can still import the old file format.

2021-09-07 14:43 UTC, PhotoNomad0 commented on __tests__/resources/acts_1_11.aligned.oldformat.usfm
> +\zaln-s |x-strong="G25320" x-lemma="καί" x-morph="Gr,D,,,,,,,,," x-occurrence="1" x-occurrences="1" x-content="καὶ"
ditto

2021-09-07 14:43 UTC, PhotoNomad0 commented on __tests__/resources/acts_1_4.aligned.oldformat.usfm
> +\zaln-s |x-lemma="καί" x-morph="Gr,CC,,,,,,,," x-occurrence="1" x-occurrences="1" x-strong="G25320" x-content="καὶ"
ditto

2021-11-08 11:03 UTC, PhotoNomad0 commented
@da1nerd This is probably ready to go with just the above tweaks.

2021-11-16 19:09 UTC, PhotoNomad0 approved these changes
LGTM

2021-11-16 19:31 UTC, merged